name: Tracee Build Logging

on:
  workflow_dispatch:

jobs:
  tracee-ebpf-logging:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create directory for Tracee logs
        run: mkdir -p tracee-logs

      - name: Start Tracee
        uses: pushkarpawar15/tracee-docker-action@v1

      - name: Wait briefly for Tracee to initialize
        run: sleep 5

      - name: Build the Hello World project
        run: |
          make
          ./hello

      - name: Save logs to a file
        run: |
          nohup docker logs -f tracee >> output.log 2>&1 &
          echo $! > tracee_log.pid

      - name: malicious command
        run: strace -o /dev/null ls
        
      - name: Wait for Tracee to capture events
        run: sleep 5

      

      - name: Stop Tracee
        run: |
          docker stop tracee
          kill $(cat tracee_log.pid) || true
          rm -f tracee_log.pid nohup.out
    
      - name: List Tracee logs
        run: ls -l 

      - name: Print Tracee logs
        run: |
          echo "Tracee logs:"
          cat output.log

      - name: Upload Tracee logs
        uses: actions/upload-artifact@v4
        with:
          name: tracee-ebpf-logs
          path: output.log
